package myfirst.java;
import java.util.*;
public class stablePin {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner scanner = new Scanner(System.in);
		int noofValues = scanner.nextInt();
		int[] values = new int[noofValues];
		for(int i=0;i<noofValues;i++) {
			values[i] = scanner.nextInt();
		}
		System.out.print("Pin generated by Stable and unStable numbers is "+stablePin(values));
		scanner.close();
	}
	static int stablePin(int[] values) {
		ArrayList<Integer> stable= new ArrayList<>();
		ArrayList<Integer> unStable= new ArrayList<>();
		for(int i=0;i<values.length;i++) {
			int[] frequency = new int[10];
			int number = values[i];
			while(number>0) {
				int Remainder = number%10;
				frequency[Remainder]++;
				number/=10;
			}
			Arrays.sort(frequency);
			boolean isStable = true;
			for(int j=0;j<(frequency.length)-1;j++) {
				if((frequency[j]!=frequency[j+1])&&frequency[j]!=0) {
					isStable = false;
				}
			}
			if(isStable) {
				while(values[i]>0) {
					stable.add(values[i]%10);
					values[i]/=10;
				}
			}
			else {
				while(values[i]>0) {
					unStable.add(values[i]%10);
					values[i]/=10;
				}
			}
		}
		Collections.sort(stable,Collections.reverseOrder());
		Collections.sort(unStable);
		
		return stable.get(0)*1000+stable.get(1)*100+unStable.get(0)*10+unStable.get(1);
	}

}
